apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostname
  name: hostname-VAR_SEQ
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/serve-hostname:1.1
    name: client
    command:
    - /bin/sh
    - -c
    - /serve_hostname -http=true -udp=false -port=8000 
    ports:
     - containerPort: 8000
       hostPort: VAR_SEQ
  restartPolicy: Never
