apiVersion: v1
kind: Service
metadata:
  name: hostname-VAR_SEQ
spec:
  ports:
  - port: 80
    name: host1
    protocol: TCP
    targetPort: 8000
  selector:
    run: hostname
  sessionAffinity: None
  type: NodePort
