apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
  annotations:
    kubernetes.io/ingress-bandwidth: 10M 
    kubernetes.io/egress-bandwidth: 20M 
spec:
  restartPolicy: Never
  containers:
  - image: networkstatic/iperf3
    name: iperf3-client
    command: ["sleep"]
    args: ["100h"]

# run test
# kubectl exec -it iperf3-client bash
# egress
# $ iperf3 -c SERVER_IP
# ingress
# $ iperf3 -R -c SERVER_IP


---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client-no-limit
spec:
  restartPolicy: Never
  containers:
  - image: networkstatic/iperf3
    name: iperf3-client
    command: ["sleep"]
    args: ["100h"]
