apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
spec:
  containers:
  - image: networkstatic/iperf3
    name: iperf3-server
    command: ["iperf3"]
    args: ["-s"]
    ports:
    - containerPort: 5201

