apiVersion: v1
kind: Pod
metadata:
  name: hairpin-pod
  labels:
    app: hairpin-test
spec:
  restartPolicy: Never
  containers:
    - name: porter
      image: gcr.io/kubernetes-e2e-test-images/porter-busybox:1.0
      env:
      - name: SERVE_PORT_80
        value: SERVE_PORT_80
      ports:
      - containerPort: 80
        name: server-80
        protocol: TCP
    - name: busybox
      image: k8s.gcr.io/busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "sleep 60; wget --timeout=5 -qO- SERVER_IP:80"]
