apiVersion: v1
kind: Pod
metadata:
  name: host-network-pod
spec:
  restartPolicy: Never
  hostNetwork: true
  containers:
    - name: porter
      image: k8s.gcr.io/busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while sleep 3600; do :; done"]

